services:
  app:
    build:
      context: .
      platforms:
        - linux/amd64
    image: ghcr.io/${GITHUB_USERNAME}/${GITHUB_REPO}:latest
    ports:
      - 3000:3000
    environment:
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_EMAIL=${VAPID_EMAIL}
    command: bun out/index.js
